### ISSUE TITLE
Edit log screen: time inputs should accept non-zero-padded input

### ISSUE THREAD

**Issue by blakewatson** [mateowatson/timetracker#113]
If I enter `9` for the hour instead of `09`, it's gonna error. But the backend should just auto-pad the input for me.

**Comment by mateowatson** [comment]
Yeah, I have some other plans for that too, like making it 12-hour clock based, and adding a js time picker. But for the non-js version that is a good idea. Thanks

**Comment by blakewatson** [comment]
I don’t know if GitHub has the concept of "related issues" but just gonna link to #112 right here since it's related.
