### ISSUE TITLE
Timer form: don’t display empty selects

### ISSUE THREAD

**Issue by blakewatson** [mateowatson/timetracker#52]
When first installing Timetracker, the timer card has two empty select fields. I think a better experience would be to show a text input in place of the empty select. For example:

**No existing projects?**
- display a text input for project creation
- hide the project select control
- hide the "New project" link

You could do all of the above actions server-side. And you could also do those actions for tasks, when there aren’t any existing tasks.

What do you think @mateowatson?

**Comment by mateowatson** [comment]
Sounds good, I'll work on it.

**Comment by blakewatson** [comment]
@mateowatson I already did it lol #53
