### ISSUE TITLE
Team report view doesn’t populate project and task dropdowns

### ISSUE THREAD

**Issue by blakewatson** [mateowatson/timetracker#56]
If you go to a team report view, the projects and task `select` fields aren’t populated.

<img width="1215" alt="Screen Shot 2019-08-31 at 8 32 01 PM" src="https://user-images.githubusercontent.com/801425/64070756-b0e6fa00-cc2e-11e9-86f1-bdd8570faaac.png">

<img width="1215" alt="Screen Shot 2019-08-31 at 8 32 56 PM" src="https://user-images.githubusercontent.com/801425/64070762-b6444480-cc2e-11e9-8ba1-fdd67ed422a3.png">

**Comment by blakewatson** [comment]
@mateowatson I'm meant to say that it works on personal but not on teams.

**Comment by mateowatson** [comment]
fixed
