### ISSUE TITLE
Investigate using Turbolinks

### ISSUE THREAD

**Issue by blakewatson** [mateowatson/timetracker#70]
At this point we should probably consider Turbolinks. It probably does what we are trying to do but better.

**Comment by blakewatson** [comment]
### Initial findings

Turbolinks does make the app feel very fast. There might be some code changes we need to make on our end to make sure it works in every situation.

There are some Turbolinks benefits I’m interested in, though:

- It merges the head, which seems like a good thing.
- It works with the back button—this is a huge problem with the current setup. I should probably file a bug.
- It _may_ do a safer body swap than what we’re doing. I don’t know, but it’s possible there’s a problem with the way we do it that I haven’t considered.

**Comment by mateowatson** [comment]
> It works with the back button—this is a huge problem with the current setup.

What do you mean? Is the back button not working?

**Comment by mateowatson** [comment]
We decided not to do turbolinks.
